apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: provider
  name: provider
spec:
  replicas: 3
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
        - image: spring-cloud-provider-demo:0.0.1
          name: spring-cloud-provider-demo
          ports:
            - containerPort: 9999
          env:
            - name: consulIp
              #替换为consul cluster ip
              value: 10.98.83.145
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

