server:
  port: 9999
spring:
  mvc:
    servlet:
      # 不能配置为/practice，否则健康检查不通过，服务发现不了
      path: /
      loadOnStartup: 1
    throw-exception-if-no-handler-found: true
    # actuator单独使用一个端口，避免与业务端口共用一个path
#management:
#  server:
#    port: 19999